#!/usr/bin/env python
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import argparse
import subprocess

import pandas as pd
from pandas.errors import EmptyDataError

from sexvary.backend_health import parse_restore_commands
from sexvary.utils import project_root


def main() -> None:
    parser = argparse.ArgumentParser(description="Execute restore commands from backend health mismatches.")
    parser.add_argument(
        "--checklist-path",
        default="results/tables/backend_health_restore_checklist.csv",
        help="CSV checklist generated by run_backend_health_report.py",
    )
    parser.add_argument(
        "--pipeline-id",
        action="append",
        help="Optional pipeline id(s) to restore. Defaults to all checklist rows.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the restore commands without executing them.",
    )
    args = parser.parse_args()

    root = project_root(__file__)
    checklist_path = Path(args.checklist_path)
    if not checklist_path.is_absolute():
        checklist_path = root / checklist_path
    if not checklist_path.exists():
        raise SystemExit(f"Restore checklist not found: {checklist_path}")

    try:
        checklist_df = pd.read_csv(checklist_path)
    except EmptyDataError:
        print("[restore] restore checklist is empty")
        return
    commands = parse_restore_commands(
        checklist_df,
        pipeline_ids=set(args.pipeline_id or []),
    )
    if not commands:
        print("[restore] no matching restore actions found")
        return

    failures = 0
    for item in commands:
        print(f"[restore] {item['pipeline_id']}: {item['command']}")
        if args.dry_run:
            continue
        completed = subprocess.run(item["argv"], text=True, capture_output=True, check=False)
        if completed.returncode != 0:
            failures += 1
            if completed.stderr.strip():
                print(completed.stderr.strip(), file=sys.stderr)
        elif completed.stdout.strip():
            print(completed.stdout.strip())

    if failures:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
